-- Create Instructors table
CREATE OR REPLACE TABLE DS5111_SU24.ZSK4GM.INSTRUCTORS (
    INSTRUCTORNAME VARCHAR(255) PRIMARY KEY,
    ISACTIVE BOOLEAN
);

-- Create Courses table
CREATE OR REPLACE TABLE DS5111_SU24.ZSK4GM.COURSES (
    COURSEMNEMONIC VARCHAR(255) PRIMARY KEY,
    COURSENAME VARCHAR(255),
    COURSEDESCRIPTION VARCHAR(255),
    ISACTIVE BOOLEAN
);

-- Create LearningOutcomes table
CREATE OR REPLACE TABLE DS5111_SU24.ZSK4GM.LEARNINGOUTCOMES (
    COURSEMNEMONIC VARCHAR(255),
    OUTCOMEDESCRIPTION VARCHAR(255) PRIMARY KEY,
    ISACTIVE BOOLEAN,
    FOREIGN KEY (COURSEMNEMONIC) REFERENCES DS5111_SU24.ZSK4GM.COURSES(COURSEMNEMONIC)
);

-- Create Assignments table
CREATE OR REPLACE TABLE DS5111_SU24.ZSK4GM.ASSIGNMENTS (
    ASSIGNMENTID NUMBER(38,0) PRIMARY KEY,
    COURSEMNEMONIC VARCHAR(255),
    TERM VARCHAR(255),
    FOREIGN KEY (COURSEMNEMONIC) REFERENCES DS5111_SU24.ZSK4GM.COURSES(COURSEMNEMONIC)
);

create or replace TABLE DS5111_SU24.ZSK4GM.INSTRUCTORASSIGNMENTS (
	ASSIGNMENTID NUMBER(38,0),
	INSTRUCTORNAME VARCHAR(255),
	primary key (ASSIGNMENTID, INSTRUCTORNAME),
	foreign key (ASSIGNMENTID) references DS5111_SU24.ZSK4GM.ASSIGNMENTS(ASSIGNMENTID),
	foreign key (INSTRUCTORNAME) references DS5111_SU24.ZSK4GM.INSTRUCTORS(INSTRUCTORNAME)
);
